name: FastAPI CRUD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: testfastdbuser
          POSTGRES_PASSWORD: testfastdbuser1234
          POSTGRES_DB: testfastdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testfastdbuser -d testfastdb"
          --health-timeout=30s
          --health-retries=3
          --health-start-period=5s

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install psycopg2  # PostgreSQL adapter for Python

    - name: Wait for PostgreSQL to be ready
      run: |
        # Wait for PostgreSQL to be ready
        until pg_isready -U testfastdbuser -d testfastdb -h localhost; do
          echo "Waiting for PostgreSQL to be ready..."
          sleep 2
        done

    - name: Run Tests
      run: |
        # Set up the DATABASE_URL environment variable for PostgreSQL
        export DATABASE_URL="postgresql+psycopg2://testfastdbuser:testfastdbuser1234@localhost:5432/testfastdb"
        pytest --maxfail=1 --disable-warnings -q  

