name: FastAPI CRUD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TESTING: true

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Set up GCP credentials
      env:
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      run: |
        # Ensure GCP_CREDENTIALS is not empty
        if [ -z "$GCP_CREDENTIALS" ]; then
          echo "GCP_CREDENTIALS is empty. Please check your secret.";
          exit 1;
        fi
        # Write the secret to a file and reformat the JSON
        echo "$GCP_CREDENTIALS" > db_cred.json
        cat db_cred.json | python -m json.tool > valid_db_cred.json
        mv valid_db_cred.json db_cred.json
        export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/db_cred.json

    - name: Debug JSON File
      run: |
        echo "Validating db_cred.json:"
        cat db_cred.json
        python -m json.tool db_cred.json

    - name: Run Tests
      run: pytest
